name: Build Debug APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Force Create Project Structure
        run: |
          # Agar koi file missing hai toh ye command use theek kar degi
          flutter create --overwrite .
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kist-app-final
          path: build/app/outputs/flutter-apk/app-debug.apk




